# utils.desirability.DBox { #spotdesirability.utils.desirability.DBox }

```python
utils.desirability.DBox(low, high, tol=None, missing=None)
```

Implements a box-like desirability function.

The desirability function assigns a value of 1 for inputs within the range `[low, high]`
and a value of 0 for inputs outside this range.

## Attributes {.doc-section .doc-section-attributes}

| Name    | Type             | Description                                                               |
|---------|------------------|---------------------------------------------------------------------------|
| low     | [float](`float`) | The lower threshold for the desirability function.                        |
| high    | [float](`float`) | The upper threshold for the desirability function.                        |
| tol     | [float](`float`) | A tolerance value to replace desirability values of 0. Defaults to None.  |
| missing | [float](`float`) | The value to use for missing inputs. Defaults to a non-informative value. |

## Functions {.doc-section .doc-section-functions}


Predicts the desirability values for the given input data.


Plots the desirability function.

## References {.doc-section .doc-section-references}

Many thanks to Max Kuhn for his implementation of the 'desirability' package in R.
This class is based on the 'desirability' package in R, see:
https://cran.r-project.org/package=desirability

## Examples {.doc-section .doc-section-examples}

```{python}
from spotdesirability import DBox
import numpy as np
import matplotlib.pyplot as plt
# Create a DBox object
dbox = DBox(low=-1.682, high=1.682)
# Predict desirability for a range of inputs
inputs = np.array([-3, -1.682, 0, 1.682, 3])
desirability = dbox.predict(inputs)
print(desirability)
# [0. 1. 1. 1. 0.]
# Plot the desirability function
dbox.plot()
```

## Methods

| Name | Description |
| --- | --- |
| [](`~spotdesirability.utils.desirability.DBox.plot`) | Plots the box-like desirability function. |
| [](`~spotdesirability.utils.desirability.DBox.predict`) | Predicts the desirability values for the given input data. |